"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { use } from "react";
import { api, errorMessage, errorCode } from "@/lib/api";
import type { ReportResponse } from "@/lib/types";
import { queryKeys } from "@/lib/query-keys";
import { PageFade } from "@/components/motion";
import { Button } from "@/components/ui/button";
import { InlineError, EmptyState } from "@/components/ui/feedback";
import { ScoreRing } from "@/components/ui/score-ring";
import { SeverityBadge, StatusBadge, OriginBadge } from "@/components/ui/badge";
import { useToast } from "@/components/ui/toast";
import { formatDateTime } from "@/lib/format";

export default function ReportPage({ params }: { params: Promise<{ caseId: string }> }) {
  const { caseId } = use(params);
  const queryClient = useQueryClient();
  const toast = useToast();

  const { data, isLoading, isError, error } = useQuery({
    queryKey: queryKeys.report(caseId),
    queryFn: () => api.get<ReportResponse>(`/cases/${caseId}/report`),
    retry: false,
  });

  const generateMutation = useMutation({
    mutationFn: () => api.post<ReportResponse>(`/cases/${caseId}/report`),
    onSuccess: async () => {
      toast.showToast("Scorecard generated from current findings and review decisions.", "success");
      await queryClient.invalidateQueries({ queryKey: queryKeys.report(caseId) });
    },
    onError: (mutationError) => toast.showToast(errorMessage(mutationError), "error"),
  });

  function downloadJson() {
    if (!data) return;
    const blob = new Blob([JSON.stringify(data.payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `shramai-scorecard-${data.payload.case.code}.json`;
    anchor.click();
    URL.revokeObjectURL(url);
    toast.showToast("Scorecard JSON downloaded.", "success");
  }

  if (isLoading) {
    return (
      <div className="card">
        <div className="card-body">
          <p className="text-muted text-small">Loading scorecard…</p>
        </div>
      </div>
    );
  }

  if (isError && errorCode(error) === "conflict") {
    return (
      <PageFade>
        <div className="card">
          <EmptyState
            title="No scorecard generated yet"
            description="Generate a screening scorecard snapshot from the current findings and review decisions. The snapshot is immutable and fully traceable."
            action={
              <Button
                variant="primary"
                loading={generateMutation.isPending}
                onClick={() => generateMutation.mutate()}
              >
                Generate scorecard
              </Button>
            }
          />
        </div>
      </PageFade>
    );
  }

  if (isError) {
    return <InlineError message={errorMessage(error)} requestId={null} />;
  }

  return (
    <PageFade>
      {data ? (
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <section className="card">
            <div className="card-header">
              <div>
                <h2 className="card-title">Screening scorecard</h2>
                <p className="card-subtitle">
                  Snapshot {formatDateTime(data.created_at)} · generated by{" "}
                  {data.payload.generated_by}
                </p>
              </div>
              <div className="page-actions">
                <Button variant="secondary" onClick={downloadJson}>
                  Download JSON
                </Button>
                <Button
                  variant="primary"
                  loading={generateMutation.isPending}
                  onClick={() => generateMutation.mutate()}
                >
                  Regenerate
                </Button>
              </div>
            </div>
            <div className="card-body" style={{ display: "flex", gap: 24, flexWrap: "wrap", alignItems: "center" }}>
              <ScoreRing score={data.score} label={data.risk_level} />
              <div style={{ display: "flex", gap: 26, flexWrap: "wrap" }}>
                <Metric label="Documents" value={data.payload.counts.documents} />
                <Metric label="Findings" value={data.payload.counts.findings} />
                <Metric label="Confirmed" value={data.payload.counts.confirmed} />
                <Metric label="Needs review" value={data.payload.counts.needs_review} />
                <Metric label="Dismissed" value={data.payload.counts.dismissed} />
              </div>
            </div>
          </section>

          <div className="info-banner">
            <span aria-hidden>ⓘ</span>
            <div>
              <strong>Screening aid only.</strong> {data.payload.disclaimer}
              <br />
              <span className="text-small">
                Score formula: {data.payload.score_explanation}
              </span>
            </div>
          </div>

          <section className="card">
            <div className="card-header">
              <div>
                <h2 className="card-title">Provenance</h2>
                <p className="card-subtitle">Every finding is traceable to a check or a model run</p>
              </div>
            </div>
            <div className="card-body" style={{ display: "grid", gap: 8 }}>
              <p className="text-small">
                <strong>Rule versions:</strong>{" "}
                {data.payload.provenance.rule_versions.join(", ") || "—"}
              </p>
              {data.payload.provenance.ai_runs.length === 0 ? (
                <p className="text-small text-muted">
                  No AI model runs recorded for this case (deterministic rules only).
                </p>
              ) : (
                data.payload.provenance.ai_runs.map((run, index) => (
                  <p className="text-small text-muted" key={index}>
                    AI run: {run.provider}/{run.model || "n/a"} · status {run.status} · prompt v
                    {run.prompt_version || "—"} · {run.findings_produced} finding(s) kept,{" "}
                    {run.findings_rejected_ungrounded} rejected (ungrounded evidence)
                  </p>
                ))
              )}
            </div>
          </section>

          <section style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            {data.payload.findings.map((finding) => (
              <article key={finding.id} className="finding-card">
                <div className="finding-top">
                  <div className="finding-badges">
                    <SeverityBadge severity={finding.severity} />
                    <StatusBadge status={finding.status} />
                    <OriginBadge origin={finding.origin} />
                  </div>
                  <span className="mono text-muted">
                    {finding.rule_id} · {finding.rule_version}
                  </span>
                </div>
                <h3 style={{ marginTop: 10 }}>{finding.title}</h3>
                <p className="explanation">{finding.explanation}</p>
                <div className="evidence-box">
                  <div className="evidence-label">Evidence</div>
                  {finding.evidence.quote ? (
                    <blockquote>&ldquo;{finding.evidence.quote}&rdquo;</blockquote>
                  ) : (
                    <span className="evidence-absent">Absence signal (evidence not found).</span>
                  )}
                  <div className="evidence-meta">
                    <span>Document: {finding.document.filename}</span>
                    {finding.evidence.page !== null ? (
                      <span>Page {finding.evidence.page}</span>
                    ) : null}
                    <span>{finding.confidence}% confidence</span>
                    {finding.review.reviewed_at ? (
                      <span>
                        Reviewed {formatDateTime(finding.review.reviewed_at)}
                        {finding.review.note ? ` — “${finding.review.note}”` : ""}
                      </span>
                    ) : (
                      <span>Not yet reviewed</span>
                    )}
                  </div>
                </div>
              </article>
            ))}
          </section>
        </div>
      ) : null}
    </PageFade>
  );
}

function Metric({ label, value }: { label: string; value: number }) {
  return (
    <div>
      <p className="stat-label">{label}</p>
      <p className="stat-value" style={{ fontSize: 22 }}>
        {value}
      </p>
    </div>
  );
}
