"""Synthetic demo document generator.

Produces a small, clearly-synthetic PDF (raw PDF syntax, no extra
dependencies) used to seed the demo workspace. Content is deliberately
labelled SYNTHETIC and intentionally omits a net-pay line so deterministic
screening rules produce a meaningful demonstration.
"""

from __future__ import annotations

LINES = [
    "SYNTHETIC DEMO PAYSLIP - NOT A REAL DOCUMENT",
    "Establishment: Ashok Industries (Synthetic Demo) Pvt. Ltd.",
    "Establishment code: SYN-000111",
    "Employee: EMP-20014 (Synthetic Worker)",
    "Pay period: 08/2026",
    "Employee Id: EMP-20014        Designation: Machine Operator",
    "Basic pay: Rs. 18,000.00",
    "HRA allowance: Rs. 4,500.00",
    "Conveyance allowance: Rs. 1,600.00",
    "Gross earnings: Rs. 24,100.00",
    "PF (provident fund) employee contribution: Rs. 1,800.00",
    "Professional tax: Rs. 200.00",
    "(The final payable figure is intentionally missing in this",
    " synthetic sample so screening rule PAY-001 has a signal.)",
    "Generated by ShramAI Inspector demo seed. No real personal data.",
]


def _escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def build_pdf_with_lines(lines: list[str]) -> bytes:
    """Build a valid one-page PDF containing the given text lines."""
    content_lines = ["BT", "/F1 10 Tf", "40 760 Td", "12 TL"]
    for line in lines:
        content_lines.append(f"({_escape(line)}) Tj T*")
    content_lines.append("ET")
    stream = "\n".join(content_lines).encode("latin-1", errors="replace")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for index, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{index} 0 obj\n".encode() + body + b"\nendobj\n"
    xref_offset = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_offset}\n%%EOF\n"
    ).encode()
    return bytes(out)


def build_synthetic_pdf() -> bytes:
    """Build the synthetic demo payslip PDF."""
    return build_pdf_with_lines(LINES)
